# Generated by Django 4.2.16 on 2026-02-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applib', '0002_author_category_alter_book_isbn_alter_book_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
    ]
