# Generated by Django 4.2.16 on 2026-02-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applib', '0004_remove_studentprofile_year_of_joining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff')], default='student', max_length=20),
        ),
    ]
