# Generated by Django 4.2.16 on 2026-02-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applib', '0006_adminprofile_address_adminprofile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='pincode',
        ),
    ]
