# Generated by Django 4.2.16 on 2026-02-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applib', '0007_remove_adminprofile_address_remove_adminprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
