# Generated by Django 6.0.1 on 2026-02-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applib', '0008_adminprofile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
