# Generated by Django 6.0.1 on 2026-02-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applib', '0009_bookissue_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregisteredstudent',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('Mech', 'Mechanical Engineering'), ('Civil', 'Civil Engineering'), ('IT', 'Information Technology'), ('AI', 'Artificial Intelligence'), ('Other', 'Other')], max_length=100),
        ),
    ]
